/** Stable API success message keys for i18n mapping on the frontend. */
const SUCCESS = {
  // Caregiver / daily records
  MEAL_INTAKE_RECORD_DELETED: 'MEAL_INTAKE_RECORD_DELETED',
  HYGIENE_RECORD_DELETED: 'HYGIENE_RECORD_DELETED',
  BEHAVIOR_RECORD_DELETED: 'BEHAVIOR_RECORD_DELETED',
  CAREGIVER_NO_ASSIGNED_RESIDENTS: 'CAREGIVER_NO_ASSIGNED_RESIDENTS',

  // Leave
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',

  // Care tasks
  CARE_TASK_ASSIGNED: 'CARE_TASK_ASSIGNED',
  CARE_TASK_DELETED: 'CARE_TASK_DELETED',

  // Auth
  AUTH_STAFF_CREATED: 'AUTH_STAFF_CREATED',
  AUTH_ACCOUNT_ACTIVATED: 'AUTH_ACCOUNT_ACTIVATED',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_RESET_EMAIL_SENT: 'AUTH_RESET_EMAIL_SENT',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_USER_UPDATED: 'AUTH_USER_UPDATED',

  // Staff
  STAFF_PROFILE_UPDATED: 'STAFF_PROFILE_UPDATED',
  STAFF_ROLE_UPDATED: 'STAFF_ROLE_UPDATED',
  STAFF_BANNED: 'STAFF_BANNED',
  STAFF_UNBANNED: 'STAFF_UNBANNED',
  STAFF_AREAS_UPDATED: 'STAFF_AREAS_UPDATED',
  STAFF_RESIDENTS_UPDATED: 'STAFF_RESIDENTS_UPDATED',

  // Resident
  RESIDENT_CREATED: 'RESIDENT_CREATED',
  RESIDENT_UPDATED: 'RESIDENT_UPDATED',
  RESIDENT_TRANSFERRED: 'RESIDENT_TRANSFERRED',
  RESIDENT_TRANSFER_NO_TARGETS: 'RESIDENT_TRANSFER_NO_TARGETS',
  RESIDENT_EMERGENCY_CONTACT_ADDED: 'RESIDENT_EMERGENCY_CONTACT_ADDED',
  RESIDENT_EMERGENCY_CONTACT_UPDATED: 'RESIDENT_EMERGENCY_CONTACT_UPDATED',
  RESIDENT_EMERGENCY_CONTACT_DELETED: 'RESIDENT_EMERGENCY_CONTACT_DELETED',
  RESIDENT_HEALTH_SAVED: 'RESIDENT_HEALTH_SAVED',
  RESIDENT_MEDICAL_HISTORY_SAVED: 'RESIDENT_MEDICAL_HISTORY_SAVED',
  RESIDENT_ALLERGIES_SAVED: 'RESIDENT_ALLERGIES_SAVED',
  RESIDENT_AVATAR_UPDATED: 'RESIDENT_AVATAR_UPDATED',

  // Meal plans / schedules / special diet
  MEAL_PLAN_DRAFT_CREATED: 'MEAL_PLAN_DRAFT_CREATED',
  MEAL_PLAN_DRAFT_UPDATED: 'MEAL_PLAN_DRAFT_UPDATED',
  MEAL_PLAN_DRAFT_DELETED: 'MEAL_PLAN_DRAFT_DELETED',
  MEAL_PLAN_PUBLISHED: 'MEAL_PLAN_PUBLISHED',
  MEAL_TIME_SCHEDULE_DRAFT_CREATED: 'MEAL_TIME_SCHEDULE_DRAFT_CREATED',
  MEAL_TIME_SCHEDULE_DRAFT_UPDATED: 'MEAL_TIME_SCHEDULE_DRAFT_UPDATED',
  MEAL_TIME_SCHEDULE_DRAFT_DELETED: 'MEAL_TIME_SCHEDULE_DRAFT_DELETED',
  MEAL_TIME_SCHEDULE_PUBLISHED: 'MEAL_TIME_SCHEDULE_PUBLISHED',
  MEAL_SPECIAL_DIET_DRAFT_CREATED: 'MEAL_SPECIAL_DIET_DRAFT_CREATED',
  MEAL_SPECIAL_DIET_DRAFT_UPDATED: 'MEAL_SPECIAL_DIET_DRAFT_UPDATED',
  MEAL_SPECIAL_DIET_DRAFT_DELETED: 'MEAL_SPECIAL_DIET_DRAFT_DELETED',
  MEAL_SPECIAL_DIET_PUBLISHED: 'MEAL_SPECIAL_DIET_PUBLISHED',

  // Dish catalog
  DISH_CREATED: 'DISH_CREATED',
  DISH_UPDATED: 'DISH_UPDATED',
  DISH_DELETED: 'DISH_DELETED',
  DISH_DEACTIVATED: 'DISH_DEACTIVATED',

  // Care schedule
  CARE_SCHEDULE_DRAFT_CREATED: 'CARE_SCHEDULE_DRAFT_CREATED',
  CARE_SCHEDULE_DRAFT_UPDATED: 'CARE_SCHEDULE_DRAFT_UPDATED',
  CARE_SCHEDULE_DRAFT_DELETED: 'CARE_SCHEDULE_DRAFT_DELETED',
  CARE_SCHEDULE_PUBLISHED: 'CARE_SCHEDULE_PUBLISHED',

  // Shifts
  SHIFT_CREATED: 'SHIFT_CREATED',
  SHIFT_UPDATED: 'SHIFT_UPDATED',
  SHIFT_PUBLISHED: 'SHIFT_PUBLISHED',
  SHIFT_CONFIRMED: 'SHIFT_CONFIRMED',
  SHIFT_COMPLETED: 'SHIFT_COMPLETED',
  SHIFT_CANCELLED: 'SHIFT_CANCELLED',
  SHIFT_DELETED: 'SHIFT_DELETED',
};

/** Vietnamese fallback success messages (server-side). */
const SUCCESS_MESSAGES = {
  [SUCCESS.MEAL_INTAKE_RECORD_DELETED]: 'Đã xóa bản ghi ăn uống',
  [SUCCESS.HYGIENE_RECORD_DELETED]: 'Đã xóa bản ghi hoạt động vệ sinh',
  [SUCCESS.BEHAVIOR_RECORD_DELETED]: 'Đã xóa bản ghi hành vi',
  [SUCCESS.CAREGIVER_NO_ASSIGNED_RESIDENTS]: 'Bạn chưa được phân công cư dân nào',

  [SUCCESS.LEAVE_SUBMITTED]: 'Đã gửi đơn nghỉ phép',
  [SUCCESS.LEAVE_APPROVED]: 'Đã duyệt đơn nghỉ phép',
  [SUCCESS.LEAVE_REJECTED]: 'Đã từ chối đơn nghỉ phép',
  [SUCCESS.LEAVE_CANCELLED]: 'Đã hủy đơn nghỉ phép',

  [SUCCESS.CARE_TASK_ASSIGNED]: 'Phân công nhiệm vụ chăm sóc thành công',
  [SUCCESS.CARE_TASK_DELETED]: 'Đã xóa nhiệm vụ chăm sóc',

  [SUCCESS.AUTH_STAFF_CREATED]: 'Tạo tài khoản nhân viên thành công',
  [SUCCESS.AUTH_ACCOUNT_ACTIVATED]: 'Kích hoạt tài khoản thành công',
  [SUCCESS.AUTH_ACCOUNT_DEACTIVATED]: 'Vô hiệu hóa tài khoản thành công',
  [SUCCESS.AUTH_PASSWORD_CHANGED]: 'Đổi mật khẩu thành công',
  [SUCCESS.AUTH_RESET_EMAIL_SENT]: 'Đã gửi email đặt lại mật khẩu',
  [SUCCESS.AUTH_PASSWORD_RESET]: 'Đặt lại mật khẩu thành công',
  [SUCCESS.AUTH_USER_UPDATED]: 'Cập nhật người dùng thành công',

  [SUCCESS.STAFF_PROFILE_UPDATED]: 'Cập nhật hồ sơ nhân viên thành công',
  [SUCCESS.STAFF_ROLE_UPDATED]: 'Cập nhật vai trò nhân viên thành công',
  [SUCCESS.STAFF_BANNED]: 'Khóa tài khoản nhân viên thành công',
  [SUCCESS.STAFF_UNBANNED]: 'Mở khóa tài khoản nhân viên thành công',
  [SUCCESS.STAFF_AREAS_UPDATED]: 'Cập nhật khu vực phân công thành công',
  [SUCCESS.STAFF_RESIDENTS_UPDATED]: 'Cập nhật cư dân được phân công thành công',

  [SUCCESS.RESIDENT_CREATED]: 'Tạo cư dân thành công',
  [SUCCESS.RESIDENT_UPDATED]: 'Cập nhật cư dân thành công',
  [SUCCESS.RESIDENT_TRANSFERRED]: 'Chuyển phòng cư dân thành công',
  [SUCCESS.RESIDENT_TRANSFER_NO_TARGETS]:
    'Không còn phòng/giường trống ở tầng đã chọn. Hãy chọn tầng khác hoặc giải phóng giường trước.',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_ADDED]: 'Đã thêm liên hệ khẩn cấp',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_UPDATED]: 'Đã cập nhật liên hệ khẩn cấp',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_DELETED]: 'Đã xóa liên hệ khẩn cấp',
  [SUCCESS.RESIDENT_HEALTH_SAVED]: 'Đã lưu tình trạng sức khỏe ban đầu',
  [SUCCESS.RESIDENT_MEDICAL_HISTORY_SAVED]: 'Đã lưu tiền sử bệnh',
  [SUCCESS.RESIDENT_ALLERGIES_SAVED]: 'Đã lưu dị ứng thuốc',
  [SUCCESS.RESIDENT_AVATAR_UPDATED]: 'Đã cập nhật ảnh đại diện cư dân',

  [SUCCESS.MEAL_PLAN_DRAFT_CREATED]: 'Tạo bản nháp kế hoạch bữa ăn thành công',
  [SUCCESS.MEAL_PLAN_DRAFT_UPDATED]: 'Cập nhật bản nháp kế hoạch bữa ăn thành công',
  [SUCCESS.MEAL_PLAN_DRAFT_DELETED]: 'Xóa bản nháp kế hoạch bữa ăn thành công',
  [SUCCESS.MEAL_PLAN_PUBLISHED]: 'Đăng kế hoạch bữa ăn thành công',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_CREATED]: 'Tạo bản nháp lịch giờ ăn thành công',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_UPDATED]: 'Cập nhật bản nháp lịch giờ ăn thành công',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_DELETED]: 'Xóa bản nháp lịch giờ ăn thành công',
  [SUCCESS.MEAL_TIME_SCHEDULE_PUBLISHED]: 'Đăng lịch giờ ăn thành công',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_CREATED]: 'Tạo bản nháp chế độ ăn đặc biệt thành công',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_UPDATED]: 'Cập nhật bản nháp chế độ ăn đặc biệt thành công',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_DELETED]: 'Xóa bản nháp chế độ ăn đặc biệt thành công',
  [SUCCESS.MEAL_SPECIAL_DIET_PUBLISHED]: 'Đăng chế độ ăn đặc biệt thành công',

  [SUCCESS.DISH_CREATED]: 'Tạo món ăn thành công',
  [SUCCESS.DISH_UPDATED]: 'Cập nhật món ăn thành công',
  [SUCCESS.DISH_DELETED]: 'Xóa món ăn thành công',
  [SUCCESS.DISH_DEACTIVATED]: 'Đã tạm ngưng món ăn vì đang được sử dụng',

  [SUCCESS.CARE_SCHEDULE_DRAFT_CREATED]: 'Tạo bản nháp lịch chăm sóc thành công',
  [SUCCESS.CARE_SCHEDULE_DRAFT_UPDATED]: 'Cập nhật bản nháp lịch chăm sóc thành công',
  [SUCCESS.CARE_SCHEDULE_DRAFT_DELETED]: 'Xóa bản nháp lịch chăm sóc thành công',
  [SUCCESS.CARE_SCHEDULE_PUBLISHED]: 'Đăng lịch chăm sóc thành công',

  [SUCCESS.SHIFT_CREATED]: 'Tạo ca làm việc thành công',
  [SUCCESS.SHIFT_UPDATED]: 'Cập nhật ca làm việc thành công',
  [SUCCESS.SHIFT_PUBLISHED]: 'Đăng ca làm việc thành công',
  [SUCCESS.SHIFT_CONFIRMED]: 'Xác nhận ca làm việc thành công',
  [SUCCESS.SHIFT_COMPLETED]: 'Xác nhận hoàn thành ca thành công',
  [SUCCESS.SHIFT_CANCELLED]: 'Hủy ca làm việc thành công',
  [SUCCESS.SHIFT_DELETED]: 'Xóa ca làm việc thành công',
};

module.exports = { SUCCESS, SUCCESS_MESSAGES };
