/** Stable API success message keys for i18n mapping on the frontend. */
const SUCCESS = {
  // Caregiver / daily records
  MEAL_INTAKE_RECORD_DELETED: 'MEAL_INTAKE_RECORD_DELETED',
  HYGIENE_RECORD_DELETED: 'HYGIENE_RECORD_DELETED',
  BEHAVIOR_RECORD_DELETED: 'BEHAVIOR_RECORD_DELETED',
  CAREGIVER_NO_ASSIGNED_RESIDENTS: 'CAREGIVER_NO_ASSIGNED_RESIDENTS',

  // Leave
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',

  // Care tasks
  CARE_TASK_ASSIGNED: 'CARE_TASK_ASSIGNED',
  CARE_TASK_DELETED: 'CARE_TASK_DELETED',

  // Auth
  AUTH_STAFF_CREATED: 'AUTH_STAFF_CREATED',
  AUTH_ACCOUNT_ACTIVATED: 'AUTH_ACCOUNT_ACTIVATED',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_RESET_EMAIL_SENT: 'AUTH_RESET_EMAIL_SENT',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_USER_UPDATED: 'AUTH_USER_UPDATED',

  // Staff
  STAFF_PROFILE_UPDATED: 'STAFF_PROFILE_UPDATED',
  STAFF_ROLE_UPDATED: 'STAFF_ROLE_UPDATED',
  STAFF_BANNED: 'STAFF_BANNED',
  STAFF_UNBANNED: 'STAFF_UNBANNED',
  STAFF_AREAS_UPDATED: 'STAFF_AREAS_UPDATED',
  STAFF_RESIDENTS_UPDATED: 'STAFF_RESIDENTS_UPDATED',

  // Resident
  RESIDENT_CREATED: 'RESIDENT_CREATED',
  RESIDENT_UPDATED: 'RESIDENT_UPDATED',
  RESIDENT_TRANSFERRED: 'RESIDENT_TRANSFERRED',
  RESIDENT_TRANSFER_NO_TARGETS: 'RESIDENT_TRANSFER_NO_TARGETS',
  RESIDENT_EMERGENCY_CONTACT_ADDED: 'RESIDENT_EMERGENCY_CONTACT_ADDED',
  RESIDENT_EMERGENCY_CONTACT_UPDATED: 'RESIDENT_EMERGENCY_CONTACT_UPDATED',
  RESIDENT_EMERGENCY_CONTACT_DELETED: 'RESIDENT_EMERGENCY_CONTACT_DELETED',
  RESIDENT_HEALTH_SAVED: 'RESIDENT_HEALTH_SAVED',
  RESIDENT_MEDICAL_HISTORY_SAVED: 'RESIDENT_MEDICAL_HISTORY_SAVED',
  RESIDENT_ALLERGIES_SAVED: 'RESIDENT_ALLERGIES_SAVED',
  RESIDENT_AVATAR_UPDATED: 'RESIDENT_AVATAR_UPDATED',

  // Meal plans / schedules / special diet
  MEAL_PLAN_DRAFT_CREATED: 'MEAL_PLAN_DRAFT_CREATED',
  MEAL_PLAN_DRAFT_UPDATED: 'MEAL_PLAN_DRAFT_UPDATED',
  MEAL_PLAN_DRAFT_DELETED: 'MEAL_PLAN_DRAFT_DELETED',
  MEAL_PLAN_PUBLISHED: 'MEAL_PLAN_PUBLISHED',
  MEAL_TIME_SCHEDULE_DRAFT_CREATED: 'MEAL_TIME_SCHEDULE_DRAFT_CREATED',
  MEAL_TIME_SCHEDULE_DRAFT_UPDATED: 'MEAL_TIME_SCHEDULE_DRAFT_UPDATED',
  MEAL_TIME_SCHEDULE_DRAFT_DELETED: 'MEAL_TIME_SCHEDULE_DRAFT_DELETED',
  MEAL_TIME_SCHEDULE_PUBLISHED: 'MEAL_TIME_SCHEDULE_PUBLISHED',
  MEAL_SPECIAL_DIET_DRAFT_CREATED: 'MEAL_SPECIAL_DIET_DRAFT_CREATED',
  MEAL_SPECIAL_DIET_DRAFT_UPDATED: 'MEAL_SPECIAL_DIET_DRAFT_UPDATED',
  MEAL_SPECIAL_DIET_DRAFT_DELETED: 'MEAL_SPECIAL_DIET_DRAFT_DELETED',
  MEAL_SPECIAL_DIET_PUBLISHED: 'MEAL_SPECIAL_DIET_PUBLISHED',

  // Dish catalog
  DISH_CREATED: 'DISH_CREATED',
  DISH_UPDATED: 'DISH_UPDATED',
  DISH_DELETED: 'DISH_DELETED',
  DISH_DEACTIVATED: 'DISH_DEACTIVATED',

  // Care schedule
  CARE_SCHEDULE_DRAFT_CREATED: 'CARE_SCHEDULE_DRAFT_CREATED',
  CARE_SCHEDULE_DRAFT_UPDATED: 'CARE_SCHEDULE_DRAFT_UPDATED',
  CARE_SCHEDULE_DRAFT_DELETED: 'CARE_SCHEDULE_DRAFT_DELETED',
  CARE_SCHEDULE_PUBLISHED: 'CARE_SCHEDULE_PUBLISHED',

  // Shifts
  SHIFT_CREATED: 'SHIFT_CREATED',
  SHIFT_UPDATED: 'SHIFT_UPDATED',
  SHIFT_PUBLISHED: 'SHIFT_PUBLISHED',
  SHIFT_CONFIRMED: 'SHIFT_CONFIRMED',
  SHIFT_CANCELLED: 'SHIFT_CANCELLED',
  SHIFT_DELETED: 'SHIFT_DELETED',
};

/** English fallback success messages (server-side). */
const SUCCESS_MESSAGES = {
  [SUCCESS.MEAL_INTAKE_RECORD_DELETED]: 'Meal intake record deleted',
  [SUCCESS.HYGIENE_RECORD_DELETED]: 'Hygiene activity record deleted',
  [SUCCESS.BEHAVIOR_RECORD_DELETED]: 'Behavior record deleted',
  [SUCCESS.CAREGIVER_NO_ASSIGNED_RESIDENTS]: 'You have no assigned residents',

  [SUCCESS.LEAVE_SUBMITTED]: 'Leave request submitted',
  [SUCCESS.LEAVE_APPROVED]: 'Leave request approved',
  [SUCCESS.LEAVE_REJECTED]: 'Leave request rejected',
  [SUCCESS.LEAVE_CANCELLED]: 'Leave request cancelled',

  [SUCCESS.CARE_TASK_ASSIGNED]: 'Care task assigned successfully',
  [SUCCESS.CARE_TASK_DELETED]: 'Care task deleted',

  [SUCCESS.AUTH_STAFF_CREATED]: 'Staff account created successfully',
  [SUCCESS.AUTH_ACCOUNT_ACTIVATED]: 'Account activated successfully',
  [SUCCESS.AUTH_ACCOUNT_DEACTIVATED]: 'Account deactivated successfully',
  [SUCCESS.AUTH_PASSWORD_CHANGED]: 'Password changed successfully',
  [SUCCESS.AUTH_RESET_EMAIL_SENT]: 'Reset password email sent',
  [SUCCESS.AUTH_PASSWORD_RESET]: 'Password reset successfully',
  [SUCCESS.AUTH_USER_UPDATED]: 'User updated successfully',

  [SUCCESS.STAFF_PROFILE_UPDATED]: 'Staff profile updated successfully',
  [SUCCESS.STAFF_ROLE_UPDATED]: 'Staff role updated successfully',
  [SUCCESS.STAFF_BANNED]: 'Staff account banned successfully',
  [SUCCESS.STAFF_UNBANNED]: 'Staff account unbanned successfully',
  [SUCCESS.STAFF_AREAS_UPDATED]: 'Assigned areas updated successfully',
  [SUCCESS.STAFF_RESIDENTS_UPDATED]: 'Assigned residents updated successfully',

  [SUCCESS.RESIDENT_CREATED]: 'Resident created successfully',
  [SUCCESS.RESIDENT_UPDATED]: 'Resident updated successfully',
  [SUCCESS.RESIDENT_TRANSFERRED]: 'Resident transferred successfully',
  [SUCCESS.RESIDENT_TRANSFER_NO_TARGETS]:
    'No vacant rooms/beds on selected floor. Choose another floor or free a bed first.',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_ADDED]: 'Emergency contact added',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_UPDATED]: 'Emergency contact updated',
  [SUCCESS.RESIDENT_EMERGENCY_CONTACT_DELETED]: 'Emergency contact deleted',
  [SUCCESS.RESIDENT_HEALTH_SAVED]: 'Initial health condition saved',
  [SUCCESS.RESIDENT_MEDICAL_HISTORY_SAVED]: 'Medical history saved',
  [SUCCESS.RESIDENT_ALLERGIES_SAVED]: 'Drug allergies saved',
  [SUCCESS.RESIDENT_AVATAR_UPDATED]: 'Resident avatar updated',

  [SUCCESS.MEAL_PLAN_DRAFT_CREATED]: 'Meal plan draft created',
  [SUCCESS.MEAL_PLAN_DRAFT_UPDATED]: 'Meal plan draft updated',
  [SUCCESS.MEAL_PLAN_DRAFT_DELETED]: 'Meal plan draft deleted',
  [SUCCESS.MEAL_PLAN_PUBLISHED]: 'Meal plan published',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_CREATED]: 'Meal time schedule draft created',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_UPDATED]: 'Meal time schedule draft updated',
  [SUCCESS.MEAL_TIME_SCHEDULE_DRAFT_DELETED]: 'Meal time schedule draft deleted',
  [SUCCESS.MEAL_TIME_SCHEDULE_PUBLISHED]: 'Meal time schedule published',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_CREATED]: 'Special diet plan draft created',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_UPDATED]: 'Special diet plan draft updated',
  [SUCCESS.MEAL_SPECIAL_DIET_DRAFT_DELETED]: 'Special diet plan draft deleted',
  [SUCCESS.MEAL_SPECIAL_DIET_PUBLISHED]: 'Special diet plan published',

  [SUCCESS.DISH_CREATED]: 'Dish created',
  [SUCCESS.DISH_UPDATED]: 'Dish updated',
  [SUCCESS.DISH_DELETED]: 'Dish deleted',
  [SUCCESS.DISH_DEACTIVATED]: 'Dish deactivated because it is in use',

  [SUCCESS.CARE_SCHEDULE_DRAFT_CREATED]: 'Care schedule draft created',
  [SUCCESS.CARE_SCHEDULE_DRAFT_UPDATED]: 'Care schedule draft updated',
  [SUCCESS.CARE_SCHEDULE_DRAFT_DELETED]: 'Care schedule draft deleted',
  [SUCCESS.CARE_SCHEDULE_PUBLISHED]: 'Care schedule published',

  [SUCCESS.SHIFT_CREATED]: 'Shift created successfully',
  [SUCCESS.SHIFT_UPDATED]: 'Shift updated successfully',
  [SUCCESS.SHIFT_PUBLISHED]: 'Shift published successfully',
  [SUCCESS.SHIFT_CONFIRMED]: 'Shift confirmed successfully',
  [SUCCESS.SHIFT_CANCELLED]: 'Shift cancelled successfully',
  [SUCCESS.SHIFT_DELETED]: 'Shift deleted successfully',
};

module.exports = { SUCCESS, SUCCESS_MESSAGES };
