const mongoose = require('mongoose');
const { PAYMENT_METHODS } = require('./enums');

const { Schema, Types } = mongoose;

const medicalRecordSchema = new Schema(
  {
    residentId: { type: Types.ObjectId, ref: 'Resident', required: true, index: true },
    createdByStaffId: { type: Types.ObjectId, ref: 'StaffProfile', index: true },
    measuredAt: { type: Date, default: Date.now, index: true },
    bloodPressureSystolic: { type: Number, min: 0 },
    bloodPressureDiastolic: { type: Number, min: 0 },
    pulse: { type: Number, min: 0 },
    temperatureCelsius: { type: Number, min: 30, max: 45 },
    oxygenSaturation: { type: Number, min: 0, max: 100 },
    bloodSugar: { type: Number, min: 0 },
    weightKg: { type: Number, min: 0 },
    heightCm: { type: Number, min: 0 },
    physicalExamination: {
      general: { type: String, trim: true },
      cardiovascular: { type: String, trim: true },
      respiratory: { type: String, trim: true },
      abdominal: { type: String, trim: true },
      neurological: { type: String, trim: true },
      musculoskeletal: { type: String, trim: true },
      skin: { type: String, trim: true },
      other: { type: String, trim: true },
      summary: { type: String, trim: true },
    },
    laboratoryTestResults: [
      {
        testName: { type: String, trim: true },
        result: { type: String, trim: true },
        unit: { type: String, trim: true },
        referenceRange: { type: String, trim: true },
        notes: { type: String, trim: true },
      },
    ],
    urinalysisResults: {
      appearance: { type: String, trim: true },
      color: { type: String, trim: true },
      pH: { type: Number, min: 0, max: 14 },
      specificGravity: { type: Number, min: 0 },
      protein: { type: String, trim: true },
      glucose: { type: String, trim: true },
      ketones: { type: String, trim: true },
      blood: { type: String, trim: true },
      leukocyteEsterase: { type: String, trim: true },
      nitrites: { type: String, trim: true },
      urobilinogen: { type: String, trim: true },
      bilirubin: { type: String, trim: true },
      microscopy: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    ecgResults: {
      heartRate: { type: Number, min: 0 },
      rhythm: { type: String, trim: true },
      prInterval: { type: String, trim: true },
      qrsDuration: { type: String, trim: true },
      qtInterval: { type: String, trim: true },
      axis: { type: String, trim: true },
      interpretation: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    imagingResults: [
      {
        modality: { type: String, trim: true },
        bodyPart: { type: String, trim: true },
        finding: { type: String, trim: true },
        impression: { type: String, trim: true },
        imageUrls: [{ type: String, trim: true }],
        cloudinaryPublicIds: [{ type: String, trim: true }],
        notes: { type: String, trim: true },
      },
    ],
    cognitiveFunction: {
      assessmentTool: { type: String, trim: true },
      score: { type: String, trim: true },
      orientation: { type: String, trim: true },
      memory: { type: String, trim: true },
      attention: { type: String, trim: true },
      language: { type: String, trim: true },
      executiveFunction: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    functionalStatus: {
      mobility: { type: String, trim: true },
      transfers: { type: String, trim: true },
      adls: { type: String, trim: true },
      iadls: { type: String, trim: true },
      assistanceRequired: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    fallRisk: {
      level: { type: String, enum: ['low', 'medium', 'high'], trim: true },
      historyOfFalls: { type: Boolean, default: false },
      gait: { type: String, trim: true },
      balance: { type: String, trim: true },
      medications: { type: String, trim: true },
      vision: { type: String, trim: true },
      cognition: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    nutritionalStatus: {
      bmi: { type: Number, min: 0 },
      weightChange: { type: String, trim: true },
      appetite: { type: String, trim: true },
      dietType: { type: String, trim: true },
      swallowing: { type: String, trim: true },
      proteinIntake: { type: String, trim: true },
      hydration: { type: String, trim: true },
      notes: { type: String, trim: true },
    },
    roomCost: { type: Number, min: 0, default: 0 },
    medicationCost: { type: Number, min: 0, default: 0 },
    careServiceCost: { type: Number, min: 0, default: 0 },
    otherCost: { type: Number, min: 0, default: 0 },
    paymentMethod: { type: String, enum: PAYMENT_METHODS },
    consentToPayment: { type: Boolean, default: false },
    invoiceId: { type: Types.ObjectId, ref: 'Invoice', index: true },
    abnormalFlag: { type: Boolean, default: false, index: true },
    summary: { type: String, trim: true },
  },
  { timestamps: true }
);

module.exports = mongoose.models.MedicalRecord || mongoose.model('MedicalRecord', medicalRecordSchema);
